version: '3.7'

services:
  nginx:
    restart: always
    image: nginx:latest
    expose:
      - 8080
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
        - web
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - 8081:8081
    depends_on:
      - db